### ISSUE TITLE
Agilent/Varian Cary binary headers

### ISSUE THREAD

**Issue by miloth** [Yohko/importtool#1]
Hi, I know it might be a long shot, but could you please share the header information on the Agilent/Varian Cary binaries? Or docs if you have it. I had a look at your script, but some bytes are skipped (understandable if that data was not interesting to you). I'd like to understand if they contain information I might want to add to our usecase. Thanks!

**Comment by Yohko** [comment]
Please send me a mail. You can find my address in my profile.
